- hosts: env_lab
  gather_facts: true
  gather_subset:
    - '!all'
    - 'min'
  strategy: free
  # roles:
  #   - { role: 9999_velociraptor_main.yml, become: yes}
  become: true
  tasks:
    - import_tasks: 3102_velociraptor_main.yml
