---
- name: Make ansible_tools directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
    state: directory
    mode: '0755'

# - name: MinIO download files velociraptor config file
#   shell: mc cp {{ MINIO_BUCKET_NAME }}/{{ MINIO_BUCKET_NAME }}/velociraptor/client.config.yaml {{ ansible_facts['user_dir'] }}/ansible_tools/velo/client.config.yaml
#   when: ansible_facts['os_family'] in ['Debian', 'Archlinux', 'RedHat']

- name: copy velociraptor config file
  copy:
    src: /Users/skywalker/ansible-lab/files/velociraptor/client.config.yaml
    dest: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/client.config.yaml"
    # dest: "/Users/skywalker/ansible-lab/files/velociraptor/client.config.yaml"
    mode: '0755'

# - name: MinIO download files velociraptor config file
#   shell: minio-client cp {{ MINIO_BUCKET_NAME }}/{{ MINIO_BUCKET_NAME }}/velociraptor/client.config.yaml {{ ansible_facts['user_dir'] }}/ansible_tools/velo/client.config.yaml
#   when: ansible_facts['os_family'] == 'FreeBSD'

# Debian : velociraptor-v0.76.1-linux-amd64
# Redhat,archlinux : velociraptor-v0.76.1-linux-amd64.musl
# freebsd : velociraptor-v0.76.1-freebsd-amd64
# github : https://github.com/Velocidex/velociraptor/releases/download/v0.75.6/velociraptor-v0.75.6-freebsd-amd64

# - name: MinIO download files velociraptor install file
#   shell: mc cp {{ MINIO_BUCKET_NAME }}/{{ MINIO_BUCKET_NAME }}/velociraptor/velociraptor-v{{ VELO_VERSION }}-linux-amd64 {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64 && chmod u+x {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64
#   when: ansible_facts['os_family'] in ['Debian', 'Archlinux']

# - name: MinIO download files velociraptor install file
#   shell: mc cp {{ MINIO_BUCKET_NAME }}/{{ MINIO_BUCKET_NAME }}/velociraptor/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl && chmod u+x {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64
#   when: ansible_facts['os_family'] in ['Redhat']

# - name: MinIO download files velociraptor install file
#   shell: mc cp {{ MINIO_BUCKET_NAME }}/{{ MINIO_BUCKET_NAME }}/velociraptor/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl && chmod u+x {{ ansible_facts['user_dir'] }}/ansible_tools/velociraptor-v{{ VELO_VERSION }}-linux-amd64
#   when: ansible_facts['os_family'] in ['Redhat'] 


###################################################
# 바이너리 파일 다운로드 github

- name: Download Debian/Archlinux binary
  command:
    cmd: curl -L -O {{ VELO_GITHUB }}/velociraptor-v{{ VELO_VERSION }}-linux-amd64
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']

- name: Download Redhat binary
  command:
    cmd: curl -L -O {{ VELO_GITHUB }}/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Download FreeBSD binary
  command:                                        
    cmd: fetch -o /usr/local/bin/velociraptor {{ VELO_GITHUB }}/velociraptor-v0.75.1-freebsd-amd64
  # args:
  #   creates: /usr/local/bin/velociraptor
  when: ansible_facts['os_family'] == 'FreeBSD'

###################################################
# 바이너리 권한 설정

- name: Change Permission velo binary
  file:
    path: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/velociraptor-v{{ VELO_VERSION }}-linux-amd64"
    mode: '0755' 
  when: ansible_facts['os_family'] in ['Debian', 'Archlinux']

- name: Change Permission velo binary
  file:
    path: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl"
    mode: '0755'
  when: ansible_facts['os_family'] == "RedHat"

- name: Change Permission velo binary
  file:
    path: "/usr/local/bin/velociraptor"
    mode: '0755'
  when: ansible_facts['os_family'] == 'FreeBSD'

###################################################
# 

- name: Make Deb file
  shell: ./velociraptor-v{{ VELO_VERSION }}-linux-amd64 --config client.config.yaml debian client
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] == 'Debian'

- name: Make rpm file
  shell: ./velociraptor-v{{ VELO_VERSION }}-linux-amd64-musl --config client.config.yaml rpm client
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] == 'RedHat'

###################################################
# archlinux 수동설치

- name: Setup Archlinux Installation
  when: ansible_facts['os_family'] == 'Archlinux'
  block:
    - name: Create config directory
      file:
        path: /etc/velociraptor
        state: directory

    - name: Copy config file
      command:
        cmd: cp {{ ansible_facts['user_dir'] }}/ansible_tools/velo/client.config.yaml /etc/velociraptor/client.config.yaml

    - name: Copy Linux binary to system path
      command:
        cmd: cp {{ ansible_facts['user_dir'] }}/ansible_tools/velo/velociraptor-v{{ VELO_VERSION }}-linux-amd64 /usr/local/bin/velociraptor

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/velociraptor_client.service
        content: |
          [Unit]
          Description=Velociraptor Client
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/velociraptor --config /etc/velociraptor/client.config.yaml client
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

###################################################
# Freebsd 수동설치

- name: Setup FreeBSD Installation
  when: ansible_facts['os_family'] == 'FreeBSD'
  block:
    - name: Create config directory
      file:
        path: /usr/local/etc/velociraptor
        state: directory

    - name: Copy config file
      command:
        cmd: cp "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/client.config.yaml" /usr/local/etc/velociraptor/client.config.yaml

    - name : make directory
      command:
        cmd: mkdir /usr/local/etc/rc.d

    - name: Create rc.d service script
      copy:
        dest: /usr/local/etc/rc.d/velociraptor_client
        mode: '0755'
        content: |
          #!/bin/sh
          # PROVIDE: velociraptor_client
          # REQUIRE: networking
          # KEYWORD: shutdown

          . /etc/rc.subr

          name="velociraptor_client"
          rcvar="velociraptor_client_enable"
          command="/usr/sbin/daemon"
          pidfile="/var/run/${name}.pid"
          velociraptor_command="/usr/local/bin/velociraptor"
          velociraptor_args="--config /usr/local/etc/velociraptor/client.config.yaml client"
          command_args="-c -f -P ${pidfile} ${velociraptor_command} ${velociraptor_args}"

          load_rc_config $name
          run_rc_command "$1"

    - name: Enable FreeBSD service in rc.conf
      lineinfile:
        path: /etc/rc.conf
        regexp: '^velociraptor_client_enable='
        line: 'velociraptor_client_enable="YES"'

    - name: Start FreeBSD service
      ansible.builtin.service:
        name: velociraptor_client
        state: started

###################################################
- name: Run install file
  shell: dpkg -i velociraptor_client_{{ VELO_VERSION }}_amd64.deb
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] in ['Debian']

- name: Run install file
  shell: rpm -ivh velociraptor_client_{{ VELO_VERSION }}_x86_64.rpm
  args:
    chdir: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
  when: ansible_facts['os_family'] in ['RedHat']

###################################################
- name: Check velociraptor service
  systemd:
    name: velociraptor_client
    state: started
    enabled: yes
  register: service_status
  when: ansible_facts['os_family'] in ['Debian', 'RedHat', 'Archlinux']

- name: Display Service Status
  ansible.builtin.debug:
    msg: "Velociraptor is OK and running!"
  when: 
    - service_status is defined
    - service_status.changed == false or service_status.state == 'started'

- name: Remove velociraptor directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/ansible_tools/velo/"
    state: absent