all:
  children:
    env_lab:
      hosts:
        beg_dmz_ns1:
        beg_dmz_ns2:
        beg_dmz_mattermost:
        beg_dmz_xroad:
        beg_dmz_satviewer:
        beg_int_ws3_31:
        beg_int_ws3_32:
        beg_int_ws3_33:
        beg_int_ws3_34:
        beg_int_ws3_35:
        beg_pgs_ntp:
        beg_pgs_dns:
        beg_scada_hmi_gt_host:
        beg_scadasub_bay2_host:
        beg_scadasub_gridpass:
        bps_dmz_ns1:
        bps_dmz_ns2:
        bps_dmz_keycloak:
        bps_dmz_xroad_ca:
        bps_dmz_xroad_cs:
        bps_dmz_xroad:
        bps_dmz_everyoneai:
        bps_dmz_tenders:
        bps_dmz_chapterheaven:
        bps_dmz_git:
        bps_dmz_nextcloud:
        bps_dmz_crm:
        bps_dmz_hr_news:
        bps_dmz_his_reg:
        bps_dmz_reporting:
        bps_dmz_voting_agent:
        bps_water_swat_historian:
        bps_water_swat_hmi:
        bps_water_swat_ews:
        bps_water_swat_plc_1:
        bps_water_swat_plc_2:
        bps_water_swat_plc_3:
        bps_water_swat_plc_4:
        bps_water_swat_plc_5:
        bps_water_swat_plc_6:
        bps_rtu_host:
        bps_int_logging:
        bps_int_voting_collector_admin:
        bps_int_voting_proxy:
        bps_int_voting_choices:
        bps_int_voting_voting:
        bps_int_voting_sessionstatus:
        bps_int_voting_storage:
      children:
        owners:
        oses:
        roles:

    owners:
      children:
        owner_dhkim:
          hosts:
            beg_pgs_ntp:
            beg_pgs_dns:
            beg_scada_hmi_gt_host:
            beg_scadasub_bay2_host:
            beg_scadasub_gridpass:
        owner_sjkim:
          hosts:
            beg_int_ws3_31:
            beg_int_ws3_32:
            beg_int_ws3_33:
            beg_int_ws3_34:
            beg_int_ws3_35:
        owner_scchoi:
          hosts:
            bps_int_logging:
            bps_int_voting_collector_admin:
            bps_int_voting_proxy:
            bps_int_voting_choices:
            bps_int_voting_voting:
            bps_int_voting_sessionstatus:
            bps_int_voting_storage:
        owner_hjyu:
          hosts:
            beg_dmz_ns1:
            beg_dmz_ns2:
            beg_dmz_mattermost:
            beg_dmz_xroad:
            beg_dmz_satviewer:

    oses:
      children:
        os_debian:
          children:
            os_ubuntu:
            os_knoppix:
        os_pacman:
          children:
            os_archlinux:
        os_rpm:
          children:
            os_fedora:
              children:
                os_rhel:
                  children:
                    os_centos:
                    os_almalinux:
                    os_rocky:
            os_opensuse:

    roles:
      children:
        role_ws:
          hosts:
            beg_int_ws3_31:
            beg_int_ws3_32:
            beg_int_ws3_33:
            beg_int_ws3_34:
            beg_int_ws3_35:
            bps_dmz_his_reg:
            bps_dmz_hr_news:
            bps_water_swat_historian:
            bps_water_swat_hmi:

        role_server:
          hosts:
            beg_dmz_ns1:
            beg_dmz_ns2:
            beg_dmz_mattermost:
            beg_dmz_xroad:
            beg_dmz_satviewer:
            beg_pgs_ntp:
            beg_pgs_dns:
            beg_scada_hmi_gt_host:
            beg_scadasub_bay2_host:
            beg_scadasub_gridpass:
            bps_int_logging:
            bps_int_voting_collector_admin:
            bps_int_voting_proxy:
            bps_int_voting_choices:
            bps_int_voting_voting:
            bps_int_voting_sessionstatus:
            bps_int_voting_storage:
            bps_dmz_keycloak:
            bps_dmz_xroad_ca:
            bps_dmz_xroad_cs:
            bps_dmz_xroad:
            bps_dmz_everyoneai:
            bps_dmz_tenders:
            bps_dmz_chapterheaven:
            bps_dmz_git:
            bps_dmz_nextcloud:
            bps_dmz_crm:
            bps_dmz_his_reg:
            bps_dmz_reporting:
            bps_dmz_voting_agent:
            bps_water_swat_ews:
            bps_water_swat_plc_1:
            bps_water_swat_plc_2:
            bps_water_swat_plc_3:
            bps_water_swat_plc_4:
            bps_water_swat_plc_5:
            bps_water_swat_plc_6:
            bps_rtu_host:


